name: Test Vite Env Secret Only
"on":
  push:
    branches: [ main ]
jobs:
  job1:
    runs-on: windows-latest
  steps:
    - name: Set env secret
      run: "echo ${{secrets.VITE_SECRET_KEY_NEW_TEST_KEY}}"
